package slim.vo.subscription;
// Generated 16 Feb, 2012 1:59:06 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SubscriptionId generated by hbm2java
 */
@Embeddable
public class SubscriptionId  implements java.io.Serializable {


     private String source;
     private String target;

    public SubscriptionId() {
    }

    public SubscriptionId(String source, String target) {
       this.source = source;
       this.target = target;
    }
   

    @Column(name="source", nullable=false, length=200)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    @Column(name="target", nullable=false, length=200)
    public String getTarget() {
        return this.target;
    }
    
    public void setTarget(String target) {
        this.target = target;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SubscriptionId) ) return false;
		 SubscriptionId castOther = ( SubscriptionId ) other; 
         
		 return ( (this.getSource()==castOther.getSource()) || ( this.getSource()!=null && castOther.getSource()!=null && this.getSource().equals(castOther.getSource()) ) )
 && ( (this.getTarget()==castOther.getTarget()) || ( this.getTarget()!=null && castOther.getTarget()!=null && this.getTarget().equals(castOther.getTarget()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSource() == null ? 0 : this.getSource().hashCode() );
         result = 37 * result + ( getTarget() == null ? 0 : this.getTarget().hashCode() );
         return result;
   }   


}


